- type: entity
  id: CrateServiceReplacementColoredLights
  name: Colored Lights Crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxColoredLighttube
        amount: 2

- type: entity
  id: CrateServiceReplacementMaintenanceLights
  name: Maintenance Lights Crate
  parent: CrateGenericSteel
  components:
  - type: StorageFill
    contents:
      - id: BoxMaintenancelightbulb
        amount: 2
